### ISSUE TITLE
Forge.py error

### ISSUE THREAD

**Issue by AndyChen2005121** [openai/neural-mmo#18]
when I tried to run `python Forge.py --render`, I got this:
```
Traceback (most recent call last):
  File "Forge.py", line 5, in <module>
    import experiments
  File "/Users/andychen/projekt/neural-mmo/experiments.py", line 2, in <module>
    from configs import Law, Chaos
  File "/Users/andychen/projekt/neural-mmo/configs.py", line 2, in <module>
    from forge.blade.core.config import Config
  File "/Users/andychen/projekt/neural-mmo/forge/blade/core/__init__.py", line 1, in <module>
    from .env import Env
  File "/Users/andychen/projekt/neural-mmo/forge/blade/core/env.py", line 8, in <module>
    from forge.blade import systems
  File "/Users/andychen/projekt/neural-mmo/forge/blade/systems/__init__.py", line 3, in <module>
    from .recipe import Recipe
  File "/Users/andychen/projekt/neural-mmo/forge/blade/systems/recipe.py", line 4
    def __init__(self, *args, amtMade=1):
                                    ^
SyntaxError: invalid syntax
```

**Comment by shuruiz** [comment]
Did you successfully install all required libs during the setup process? And can you tell us your python environment detail? Because it works well under my v3.6 environment.

**Comment by AndyChen2005121** [comment]
@shuruiz yep, I re-run setup.sh for this and checked... all the libs are fine...
```
Python 2.7.15 (default, Jan 12 2019, 21:07:57)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
```
maybe it's because of python2?
anyway on my machine python 3 is aliased to `python3`... so you mean I have to re-run the whole process?

**Comment by shuruiz** [comment]
@AndyChen2005121  I will recommend you use Python 3, e.g., Python 3.6.x. There are many syntax differences between py2 and py3.  This might be the reason that you have this issue.

**Comment by jsuarez5341** [comment]
Thanks @shuruiz -- yes, python 3.6+ for the moment.
