### ISSUE TITLE
ImportError: cannot import name 'factorial' from 'scipy.misc'

### ISSUE THREAD

**Issue by Ramm77** [openai/neural-mmo#30]
i'm just trying to run this:
import statsmodels.formula.api as sm

then i get this error:
import statsmodels.formula.api as sm
Traceback (most recent call last):

  File "<ipython-input-26-5ad1e596ef83>", line 1, in <module>
    import statsmodels.formula.api as sm

  File "c:\users\ramma\appdata\local\programs\python\python37-32\lib\site-packages\statsmodels\formula\api.py", line 15, in <module>
    from statsmodels.discrete.discrete_model import MNLogit

  File "c:\users\ramma\appdata\local\programs\python\python37-32\lib\site-packages\statsmodels\discrete\discrete_model.py", line 45, in <module>
    from statsmodels.distributions import genpoisson_p

  File "c:\users\ramma\appdata\local\programs\python\python37-32\lib\site-packages\statsmodels\distributions\__init__.py", line 2, in <module>
    from .edgeworth import ExpandedNormal

  File "c:\users\ramma\appdata\local\programs\python\python37-32\lib\site-packages\statsmodels\distributions\edgeworth.py", line 7, in <module>
    from scipy.misc import factorial

ImportError: cannot import name 'factorial' from 'scipy.misc' (c:\users\ramma\appdata\local\programs\python\python37-32\lib\site-packages\scipy\misc\__init__.py)

**Comment by jsuarez5341** [comment]
Hi, would love to help. What part of this is related to this repo?

**Comment by jsuarez5341** [comment]
Closing for inactivity; reopen if applicable
